version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - redis
      - mongo
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"