version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"